# Generated by Django 4.2.7 on 2023-11-23 19:43

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='url_image',
            field=models.ImageField(null=True, upload_to=core.models.user_image_field),
        ),
    ]
