# Generated by Django 4.2.7 on 2023-11-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_url_image_user_url_imagem_conta'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='locked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='login_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
